// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HamburgerMenuController from "./hamburger_menu_controller"
application.register("hamburger-menu", HamburgerMenuController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MachiRepos__IndexController from "./machi_repos/index_controller"
application.register("machi-repos--index", MachiRepos__IndexController)

import MachiRepos__NewController from "./machi_repos/new_controller"
application.register("machi-repos--new", MachiRepos__NewController)

import PrefectureMunicipalityController from "./prefecture_municipality_controller"
application.register("prefecture-municipality", PrefectureMunicipalityController)

import TagController from "./tag_controller"
application.register("tag", TagController)
