// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HamburgerMenuController from "./hamburger_menu_controller"
application.register("hamburger-menu", HamburgerMenuController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MachiRepoCreateController from "./machi_repo_create_controller"
application.register("machi-repo-create", MachiRepoCreateController)

import PrefectureMunicipalityController from "./prefecture_municipality_controller"
application.register("prefecture-municipality", PrefectureMunicipalityController)
