// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import DisableScrollController from "./disable_scroll_controller"
application.register("disable-scroll", DisableScrollController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GoogleMapsController from "./google_maps_controller"
application.register("google-maps", GoogleMapsController)

import HamburgerMenuController from "./hamburger_menu_controller"
application.register("hamburger-menu", HamburgerMenuController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MachiRepos__ChatController from "./machi_repos/chat_controller"
application.register("machi-repos--chat", MachiRepos__ChatController)

import MachiRepos__FormController from "./machi_repos/form_controller"
application.register("machi-repos--form", MachiRepos__FormController)

import MachiRepos__IndexController from "./machi_repos/index_controller"
application.register("machi-repos--index", MachiRepos__IndexController)

import MachiRepos__ShowController from "./machi_repos/show_controller"
application.register("machi-repos--show", MachiRepos__ShowController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PrefectureMunicipalityController from "./prefecture_municipality_controller"
application.register("prefecture-municipality", PrefectureMunicipalityController)

import ReloadController from "./reload_controller"
application.register("reload", ReloadController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import TagController from "./tag_controller"
application.register("tag", TagController)

import TextareaResizeController from "./textarea_resize_controller"
application.register("textarea-resize", TextareaResizeController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import TopController from "./top_controller"
application.register("top", TopController)
